### ISSUE TITLE
Cover integration is broken since last week checkins

### ISSUE THREAD

**Issue by tomer-w** [jdeneef/ha_gpiod#16]
Just raising awareness here for what got discovered in the integration work done on the @thecode branch: https://github.com/thecode/ha-rpi_gpio/pull/281#issuecomment-2395018229
```
entity.is_on = True if value ^ active_low else False
```
will not work as in the cover case the ```entity``` is null.

**Comment by jdeneef** [comment]
fixed it in 1.4.4

**Comment by tomer-w** [comment]
@jdeneef thanks! Let me know if you want to integrate it with the [new repo](https://github.com/thecode/ha-rpi_gpio/tree/gpiod-rpi5) or want me to do it.

**Comment by jdeneef** [comment]
If you can add it? Would be next weekend the soonest for me. Fix is simple, see below. I also fixed a typo and cover in same way as switch and sensor:
https://github.com/jdeneef/ha_gpiod/compare/v1.4.4...v1.4.5

**Comment by tomer-w** [comment]
Hey @jdeneef , I just merged it to https://github.com/thecode/ha-rpi_gpio/tree/gpiod-rpi5 but it takes good amount of effort as folder got moved and some changes we made in the code itself.
It will be great if going forward we will all work on the https://github.com/thecode/ha-rpi_gpio/tree/gpiod-rpi5 branch and hopefully merge it this week to the main branch and then use it as the source of truth.

FYI: @thecode
