### ISSUE TITLE
Problem Inputs after Power off/on

### ISSUE THREAD

**Issue by sergiosmt** [jdeneef/ha_gpiod#17]
I noticed this problem: when you do a hardware reboot or after a power off/on the GPIO inputs are in a random state (on/off) and at the first change of state they are put in the correct state. 
The problem is for automations that do not work until the first change of state. 
I have a raspberry pi5. 
I have already set all inputs to "BIAS:PULL_UP". 
If I restart the Home assistant, however, all the inputs are correctly positioned in the off state.
Thanks for the collaboration.

**Comment by jdeneef** [comment]
will need to test some more. I'm reading the sensor state before initialization, in theory that should work. Maybe adding things like ``bias`` etc might help getting better readings. Will test and share results

**Comment by jdeneef** [comment]
tested, but looks ok, only 1 sensor though ;-) Nevertheless I found some improvements. please test v1.4.6?

**Comment by sergiosmt** [comment]
Okay, thanks. 
As soon as the new version is available I'll do a test.

**Comment by sergiosmt** [comment]
Downloaded v1.4.6
I tried turning the raspberry off and on again and everything was fine, the inputs now have the correct state even immediately after the reboot.
Thank you very much for your cooperation. 
HI

**Comment by jdeneef** [comment]
nice, updated in v1.4.7 as release, thanx for testing!
