### ISSUE TITLE
bouncetime parm refused when config is checked

### ISSUE THREAD

**Issue by ecou2508** [jdeneef/ha_gpiod#2]
Hello,
I had to comment bouncetime for binary_sensor as this parm is refused...? Thanks. [Eddy]

**Comment by ecou2508** [comment]
![Capture d’écran 2024-05-19 192258](https://github.com/jdeneef/ha_gpiod/assets/50460169/9040261f-6d6c-4267-a978-df497257d2c6)

If i uncomment the bouncetime parm, i get the message below:
![Capture d’écran 2024-05-19 173404](https://github.com/jdeneef/ha_gpiod/assets/50460169/7d0678ab-ceb2-4503-88f4-07230ab6a01d)

**Comment by jdeneef** [comment]
I seem to have renamed `bouncetime` to `debounce`, can you test? I will adjust the `readme`
from: `CONF_DEBOUNCE= "debounce"`, because the `gpiod` port config is `debounce_period`

**Comment by ecou2508** [comment]
Hi ! works great :-)
Thank you for a so quick action !

Eddy

**Comment by jdeneef** [comment]
Nice
