### ISSUE TITLE
RF reading

### ISSUE THREAD

**Issue by TonsiTT** [jdeneef/ha_gpiod#8]
I have a rf reciever connected to gpio pins. Do you think it would be possible to read the codes from them via this addon?

**Comment by jdeneef** [comment]
I'm no expert, but I don't think so. The python `GPIOD` library is  for reading/writing `on`/`off`. For addressing something like an RF receiver you probably need UART functionality which can be addressed using the pythons `serial` library.

**Comment by jdeneef** [comment]
closing
